### PR TITLE
Upgrade to Cucumber 3.0

### PR DESCRIPTION
**Pull request by DirtyF**
Tests are passing but the `print_stats` method is now undefined.

```sh
undefined method `print_stats' for #<Jekyll::Cucumber::Formatter:0x007fa12cbeba48> (NoMethodError)
/Users/frank/code/jekyll/jekyll/features/support/formatter.rb:210:in `print_summary'
/Users/frank/code/jekyll/jekyll/features/support/formatter.rb:49:in `after_features'
```

Breaking change introduced in https://github.com/cucumber/cucumber-ruby/pull/999

### CODE REVIEW

**Comment by pathawks** [comment]
https://github.com/cucumber/cucumber-ruby/pull/999#discussion-diff-71759600

`print_stats` is now `print_statistics`

**Comment by pathawks** [comment]
Fixes #6394

**Comment by DirtyF** [comment]
@pathawks I thought we could go with the new `summary` format for now. 
The only difference is that it doesn't print the time for each test.

Plus the following warning message implies that if we want to continue to customize the cucumber tests outputs, some refactoring will be necessary one day or another:

```
WARNING: The formatter Jekyll::Cucumber::Formatter is using the deprecated formatter API which will be removed in v4.0 of Cucumber.
```

Could we tackle this in another PR?

**Comment by pathawks** [comment]
> Could we tackle this in another PR?

Yeah, let’s do. :+1:

File: script/cucumber [hunk 1]
```diff
@@ -1,4 +1,3 @@
 #!/usr/bin/env bash
 
-time ruby -S bundle exec cucumber \
-  -f Jekyll::Cucumber::Formatter "$@"
+time ruby -S bundle exec cucumber --format summary
```
Comment (pathawks) [inline script/cucumber]: Just for Git History, could we leave line 3 as is?

```sh
time ruby -S bundle exec cucumber \
  --format summary
```

**Comment by pathawks** [comment]
Thanks @DirtyF.

I'm looking at using the new events API to get our timing information :+1:

File: script/cucumber (hunk 1 above)
Comment (DirtyF) [reply script/cucumber]: Done.

**Comment by DirtyF** [comment]
@pathawks  ❤️ 

Here is the summary display (very readable if you ask me)

cucumber-summary-jekyll

and the final summary:

```sh
212 scenarios (212 passed)
1763 steps (1763 passed)
4m16.614s
```

**Comment by ashmaroli** [comment]
Wow.. nice..
Can you post a view for a failing test too..? (easily done locally..)

**Comment by ashmaroli** [comment]
also I think this leaves `/features/support/formatter.rb` reduntant..

File: script/cucumber [hunk 2]
```diff
@@ -1,4 +1,4 @@
 #!/usr/bin/env bash
 
 time ruby -S bundle exec cucumber \
-  -f Jekyll::Cucumber::Formatter "$@"
+-f summary "$@"
```
Comment (ashmaroli) [inline script/cucumber]: It'd be nice to leave the indentation as ln#4 is a continuation of ln#3.. instead of a new expression..

**Comment by pathawks** [comment]
> also I think this leaves `/features/support/formatter.rb` reduntant..

No, I'm working on adding back some of that functionality. Let's keep it there.

**Comment by pathawks** [comment]
cuc

Abbreviated to only show one group, but you can get the gist.

**Comment by pathawks** [comment]
I added a commit that will more closely resemble the previous output of Cucumber, but without using our own formatter.

This is just a first pass, and I tried to change as little as reasonable. Much of `features/support/formatter.rb` really could probably be removed, and I'm not sure if just sticking `AfterConfiguration` at the end is a good idea.

@DirtyF Feel free to change anything I added or just remove my commit altogether. Either way, I'm good upgrading to Cucumber 3.0 and we can tweak things as we go if need be.

**Comment by pathawks** [comment]
ac61f65cb7363a6a46067f86316c38fd2159f807
cuc

**Comment by DirtyF** [comment]
@pathawks We'll discuss formatting in another PR. Thanks for your help on this. 🤝 
 
@jekyllbot: merge +dev
