### ISSUE TITLE
Jekyll Archives broken by Jekyll 3.3

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5417]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [ ] I was trying to install.
- [x] There is a broken Plugin API.
- [x] I was trying to build.
- [ ] It was another bug.

---

When building my site with `master`, Jekyll Archives throws this error and the build does not succeed.

```text
jekyll 3.2.1 | Error:  undefined method `extname' for #<Jekyll::Archives::Archive:0x007f8e4f0ba0b0>
```

Using the magical `git bisect`, I have traced this back to 741102bd40db3d12b2bb9221a37aefd3d6beb744, and in the process ran across this _different_ error message.

```text
jekyll 3.2.1 | Error:  undefined method `write?' for #<Jekyll::Archives::Archive:0x007fe3c79de0d8>
```

This one I can trace back to b781b9967de4386440c2f09f2e670ad34d329f4e. This is a breaking change.

To avoid breaking things, it seems we need to fix this before **3.3** ships.

**Comment by parkr** [comment]
@pathawks Can you please post a backtrace for each of them?

**Comment by pathawks** [comment]
```text
Pats-Mac-Pro:Blog pat$ bundle exec jekyll build --trace
Configuration file: ~/Dropbox/Blog/_config.yml
            Source: ~/Dropbox/Blog
       Destination: ~/Dropbox/Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
~/GitHub/jekyll/lib/jekyll/renderer.rb:38:in `block in converters': undefined method `extname' for #<Jekyll::Archives::Archive:0x007fbaf02d6380> (NoMethodError)
	from ~/GitHub/jekyll/lib/jekyll/renderer.rb:38:in `select'
	from ~/GitHub/jekyll/lib/jekyll/renderer.rb:38:in `converters'
	from ~/GitHub/jekyll/lib/jekyll/renderer.rb:68:in `run'
	from ~/GitHub/jekyll/lib/jekyll/convertible.rb:211:in `do_layout'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:174:in `block in generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:172:in `each'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:172:in `generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:68:in `process'
	from ~/GitHub/jekyll/lib/jekyll/command.rb:26:in `process_site'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:63:in `build'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:34:in `process'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from ~/GitHub/jekyll/exe/jekyll:13:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from ~/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from ~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

---

```text
Pats-Mac-Pro:Blog pat$ bundle exec jekyll build --trace
Configuration file: ~/Dropbox/Blog/_config.yml
            Source: ~/Dropbox/Blog
       Destination: ~/Dropbox/Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
~/GitHub/jekyll/lib/jekyll/renderer.rb:168:in `place_in_layouts': undefined method `write?' for #<Jekyll::Archives::Archive:0x007fdccfa89d10> (NoMethodError)
	from ~/GitHub/jekyll/lib/jekyll/convertible.rb:214:in `render_all_layouts'
	from ~/GitHub/jekyll/lib/jekyll/convertible.rb:247:in `do_layout'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from ~/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:174:in `block in generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:172:in `each'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:172:in `generate'
	from ~/GitHub/jekyll/lib/jekyll/site.rb:68:in `process'
	from ~/GitHub/jekyll/lib/jekyll/command.rb:26:in `process_site'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:63:in `build'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:34:in `process'
	from ~/GitHub/jekyll/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from ~/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from ~/GitHub/jekyll/exe/jekyll:13:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from ~/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from ~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Crunch09** [comment]
Thanks @pathawks for the stacktrace!

I think `jekyll-archives` badly needs a new release, the last one is from October 30, 2015. Since https://github.com/jekyll/jekyll-archives/commit/b02074eef7aa4dee1c1d06c167e053d18b38cd94 though `Jekyll::Archives::Archive` inherits from `Jekyll::Page` and therefore implements `extname`:
<img width="584" alt="screen shot 2016-09-28 at 20 47 10" src="https://cloud.githubusercontent.com/assets/570608/18927573/c40600ec-85bc-11e6-9daf-d36171c5936c.png">
@pathawks Can you confirm that this issue is not happening if you use `jekyll-archives` from current master?

**Comment by parkr** [comment]
@Crunch09 you rock! thanks for checking that out. It sounds like it definitely needs a release.

**Comment by pathawks** [comment]
I will take a look tonight to confirm that the issue is resolved when on **jekyll-archives** `master`.

However, it still troubles me that it works with Jekyll 3.2 but not 3.3. That's not really how semver is supposed to work.

/cc @jekyll/stability

**Comment by parkr** [comment]
@pathawks Did you figure this out?

**Comment by pathawks** [comment]
Sorry, yes. It is true that **jekyll-archives** `master` does not have this problem.

**Comment by parkr** [comment]
OK, let's get that released as well.

**Comment by pathawks** [comment]
Can we make sure there is some information about the breaking API changes in the release notes? We aren't the only ones who write Jekyll plugins.

#5442

**Comment by parkr** [comment]
@pathawks We still have the `extname` method – why is it breaking?

**Comment by geotheory** [comment]
Forgive ignorance but what is the fix for this? I'm trying to get Jekyll working and have run into this. `gem 'jekyll-archives'` is in the project Gemfile..

**Comment by ashmaroli** [comment]
@geotheory make sure you're using the latest version of `jekyll-archives` by running: 
```
$ bundle update jekyll-archives
```

**Comment by parkr** [comment]
I don't believe there has been a release for that fix, so you may need to
depend on the repository. Hopefully @alfredxing can cut a new gem soon.

**Comment by bill-mcgonigle** [comment]
2.1.1 seems to work. 

```
$ bundle update jekyll-archives
...
Using jekyll-archives 2.1.1 (was 2.1.0)
```
