### ISSUE TITLE
highlight make Liquid Exception: undefined method `t' for nil:NilClass

### ISSUE THREAD

**Issue by pureexe** [jekyll/jekyll#4258]
I'm using jekyll v.3.0.1 and write markdown with kramdown and write this code

```
{% highlight text%}
เธออายุเท่าไร
  อายุ 18 ค่ะ แล้วคุณอายุของคุณเท่าไรคะ?
    [ผม|ฉัน][อายุ]*[ครับ|ค่ะ]
      คุณนี่ดู{{1}>18?เด็ก:แก่}จังเลยค่ะ
{% endhighlight%}
```

then it got error `Liquid Exception: undefined method 't' for nil:NilClass`

look like liquid parse inside highlight tag and error at `{{1}` .
so can you solve this problem by prevent liquid parse in highlight  tag?

or i need to report this issue to liquid repository?

best regrad and sorry for my bad english.

**Comment by envygeeks** [comment]
At this time there is nothing we can do about that other than recommend you wrap it in {% raw %} {% endraw %}.   So that it does not process what looks like liquid or what should be liquid for display.  If this is not your intention please do give us more context.

**Comment by parkr** [comment]
@pureexe, Yes please wrap with `{% raw %}`. This also looks like #4173, which was fixed by #4174.

For now, try

```liquid
{% highlight text %}
{% raw %}
เธออายุเท่าไร
  อายุ 18 ค่ะ แล้วคุณอายุของคุณเท่าไรคะ?
    [ผม|ฉัน][อายุ]*[ครับ|ค่ะ]
      คุณนี่ดู{{1}>18?เด็ก:แก่}จังเลยค่ะ
{% endraw %}
{% endhighlight %}
```

**Comment by pureexe** [comment]
thank you for solution.
it's work fine on Jekyll 3.0.1

**Comment by jiler** [comment]
I solved my problem by delete the blank lines, which located between beginning(ending) sign and the first(last) line code. Just like the flowing codes:
before: 
    `{% highlight ruby %}

     def show(name)
        puts "hi, #{name}"
     end

    {% endhighlight %}
    `
after:
    `{% highlight ruby %}
      def show(name)
         puts "hi, #{name}"
      end
     {% endhighlight %}
    `
