### ISSUE TITLE
New Drops::DocumentDrop page object doesn't support .fetch() method

### ISSUE THREAD

**Issue by fcassirer** [jekyll/jekyll#4615]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
CentOS 7.2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Executing a plugin function that looks up dotted names and returns jekyll hash values, i.e., "site.baseurl", "page.url", etc.  Recursively does this function, i.e.,:

 def lookup(context, name)                                                                                                    
 31      lookup = context                                                                                                           
 32      name.split(".").each { |value| lookup = lookup[value] }                                                                    
 33      lookup                                                                                                                     
 34    end           

###### What did you expect to see?

The value of context.registers[:page]['url']

###### What did you see instead?
NoMethodError: undefined method `fetch' for #<Jekyll::Drops::DocumentDrop:0x00000003390410>

The issue is that there seems to be a new object type, Jekyll::Drops:DocumentDrop introduced in commit 82c3ee365f5a8b948ce2ea853d75a954fa709939, full text:

   Initial work on using Liquid::Drops instead of Hashes.  …
   parkr committed on Dec 21, 2015
   The properties of Liquid::Drops are only evaluated when they're asked for
   and therefore save computation time. This prevents a lot of GC time cleaning
   up objects that are not needed, because they're not created unless requested.
   Additionally, this saves time for actual computation of those values because
   they can be computed only if needed.
   It's funny how much it helps when you only do what is needed. Far less overhead.

The new object doesn't support the standard '.fetch()' method on hashes.  As such, it behaves differently than other non-page objects ... 

i.e:

ls lookup
Liquid::Drop#methods: before_method  context=  has_key?  invoke_drop  to_liquid
Jekyll::Drops::Drop#methods: []  []=  content_methods  each_key  inspect  key?  keys  merge  merge!  to_h  to_hash
Jekyll::Drops::DocumentDrop#methods: 
  collection  content  excerpt  fallback_data  id  next  output  path  previous  relative_path  to_s  url
instance variables: @content_methods  @context  @mutations  @obj

and a standard hash:
ls {}
Enumerable#methods: 
  all?            count       each_cons         entries     flat_map  map     minmax     reduce        take      
  any?            cycle       each_entry        find        grep      max     minmax_by  reverse_each  take_while
  chunk           detect      each_slice        find_all    group_by  max_by  none?      slice_before  to_set    
  collect         drop        each_with_index   find_index  inject    min     one?       sort          zip       
  collect_concat  drop_while  each_with_object  first       lazy      min_by  partition  sort_by     
JSON::Ext::Generator::GeneratorMethods::Hash#methods: to_json
Hash#methods: 
  ==                    default        each_key    has_key?    keep_if  merge!              replace  to_h       values_at
  []                    default=       each_pair   has_value?  key      pretty_print        select   to_hash  
  []=                   default_proc   each_value  hash        key?     pretty_print_cycle  select!  to_liquid
  assoc                 default_proc=  empty?      include?    keys     rassoc              shift    to_s     
  clear                 delete         eql?        index       length   rehash              size     update   
  compare_by_identity   delete_if      fetch       inspect     member?  reject              store    value?   
  compare_by_identity?  each           flatten     invert      merge    reject!             to_a     values   

This breaks a *bunch* of code ... sure, I can work around it, but it seems that having to special case each object type complicates plugin code when in fact you are looking to greatly reduce the complications.  

If there are better, less fragile ways to do the lookup please let me know.
Thanks for any feedback ... good stuff.

-Fred Cassirer

**Comment by parkr** [comment]
@fcassirer Sorry about this? We can certainly add in some methods to make drops work a bit more like hashes. Can you provide a list of methods you would like to see added? I couldn't really tell from your message.

**Comment by fcassirer** [comment]
No worries, easy enough to work around, thanks.  Just from a philosophical view, I think I could write more robust plugins if I could be sure there were a core set of methods across all objects.  I had issues with an earlier release where the to_yaml method didn't exist on some objects and I had to special case things.  Here, if I could assume any page-ish object (Document, Page, Collection, Post, etc) was a hash at its core (or all were built around a base object) I wouldn't have to tweak code so much with every update when the next cool and useful object type is used for one of the jekyll objects ;-)

I tend to use .fetch() alot because without heroics, ruby doesn't autovivify, Sorry about the formatting above, the pry_debug method dump didn't format nicely here.

Thanks
-FredC

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least
three months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If you can still reproduce this error on the <code>3.1-stable</code> or <code>master</code> branch,
please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider building it first as a plugin. Jekyll 3 introduced
[hooks](http://jekyllrb.com/docs/plugins/#hooks) which provide convenient access points throughout
the Jekyll build pipeline whereby most needs can be fulfilled. If this is something that cannot be
built as a plugin, then please provide more information about why in order to keep this issue open.

Thank you for all your contributions.

**Comment by michaelbrundage** [comment]
I'm also hitting this, after upgrading from Jekyll 3.0.1 to 3.1.6. I had a custom Liquid::Tag with 

```ruby
    def render(context)
      page = context[@name]
      site = context.registers[:site]
      p = (page.fetch('published', true) || page.fetch('link', false)) && !site.unpublished
      ...
```

and now that fails because page.fetch isn't a method.

**Comment by parkr** [comment]
This should be fairly straight-forward to implement. Please submit a PR
that adds this method to `Drops::Drop` located in
<code>lib/jekyll/drops/drop.rb</code> Please add a quick test for it as
well. Thanks!
