### ISSUE TITLE
Jekyll serve --watch stopped working

### ISSUE THREAD

**Issue by nohorbee** [jekyll/jekyll#5477]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

jekyll serve --watch suddenly stopped regenerating the site on filesystem changes.
Checking at the recent events, I updated from OSX El Capitan to OSX Sierra. I don't know if it is related but I can't think of any other things. I'm not getting any error message. If I stop and run jekyl serve --watch again, the site gets refreshed

**Comment by pathawks** [comment]
Can you please provide more information? What version of Jekyll are you using?

**Comment by goyllo** [comment]
I have upgrade my site to jekyll 3.3 recently and  jekyll server also not working in my windows 7. It says --watch arg is not supported in windows. Here another guy facing same problem - http://stackoverflow.com/questions/39970672/watch-arg-is-unsupported-on-windows

**Comment by bomberstudios** [comment]
I'm seeing a similar issue here, but I think it's only happening with collections. Jekyll prints a `Regenerating: 1 file(s) changed at 2016-10-13 10:34:00 ...done in 2.896059 seconds.` message but the file does not seem to be updated on disk.

I would appreciate more info from the original reporter to make sure it's the same issue and not something else (I have a few ideas of what might be happening, but more info is always a good thing : )

Here's my Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.4.0)
    colorator (1.1.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.0.1)
    ffi (1.9.14)
    forwardable-extended (2.6.0)
    hawkins (2.0.4)
      em-websocket (~> 0.5)
      jekyll (~> 3.1)
    http_parser.rb (0.6.0)
    jekyll (3.3.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-contentblocks (1.2.0)
      jekyll
    jekyll-redirect-from (0.11.0)
      jekyll (>= 2.0)
    jekyll-sass-converter (1.4.0)
      sass (~> 3.4)
    jekyll-sitemap (0.11.0)
      addressable (~> 2.4.0)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.12.0)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)

PLATFORMS
  ruby

DEPENDENCIES
  hawkins (~> 2.0, >= 2.0.4)
  jekyll
  jekyll-contentblocks
  jekyll-redirect-from
  jekyll-sitemap

BUNDLED WITH
   1.13.2
```

**Comment by goyllo** [comment]
It's not about the collection. all windows user getting same problem. 
https://github.com/jekyll/jekyll/issues/5462

**Comment by bomberstudios** [comment]
FTR, I'm also seeing the issue with Jekyll 3.2.1, so my problem _might_ be unrelated to this.

**Comment by bomberstudios** [comment]
Can confirm that my issue is in fact unrelated to the `--watch` option, so please ignore my previous comment : )

**Comment by pathawks** [comment]
Closing as duplicate of #5462

**Comment by nohorbee** [comment]
Sorry for the delay. This doesn't seem to be a duplicate. I'm using a really old version of Jekyll but it was working perfectly. jekyll 2.5.3
--
I'm using it on a Mac and, as I said, I suspect it is related to the Sierra update

**Comment by ashmaroli** [comment]
Why don't you try upgrading Jekyll to 3.3.0 as well?

**Comment by nohorbee** [comment]
I am running some plugins (https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin) and apparently, it generates a conflict with this version. After updating, I get "jekyll 3.2.1 | Error:  undefined method `priority' for Jekyll::Paginate::Pagination:Class". I still don't know how to walkthrough this

**Comment by pathawks** [comment]
@nohorbee Sounds like an issue with the plugin. **jekyll-paginate** is no longer supported, for what it is worth.

**Comment by nohorbee** [comment]
Yes, but I don't exactly know how to proceed. I'm not sure how to disable pagination (or if the multilingual plugin still need it)

**Comment by ashmaroli** [comment]
Do you have your site source code on the internet? If yes, please provide link.

**Comment by nohorbee** [comment]
Apparently, my problem is here: https://github.com/ourbit/ourbit.github.io/blob/source/_plugins/language_generator.rb

I have this plugin necessary for pages such as:
- https://github.com/ourbit/ourbit.github.io/blob/source/_layouts/multilingual-archives.html
- https://github.com/ourbit/ourbit.github.io/blob/source/_layouts/multilingual-index.html

**Comment by nohorbee** [comment]
Ok. Back here. I refactored my site and now is working with Jekyll 3.2.1 (I'm glad I merged to it).

I kept editing my file and noticing that --watch was "not working". I decided to modify a different file and "bingo". It was working. So, I started playing with the file that is generating the problem (changing the name of it, making it shorter and longer). It will be hard to believe or even reproduce. I'm only having the "no automatic site regeneration issue" when the file is named "2016-10-10-predictability-lesson-learned.markdown" or "2016-10-10-predictability-lesson.markdown" (actually, everything like this: 2016-10-10-predictability-lesson*.markdown seems to reproduce the bug).

I changed the name of the file and voila. No more problem.

In case you want to debug this, here is the commit and folder where that file was located. I hope it helps: https://github.com/ourbit/ourbit.github.io/tree/41db7deb8afdb836ef2dffefc9b7791289fe00f7/_i18n/en/_posts
